# pipeline for testing on ARM64
kind: pipeline
type: docker
name: Test on Linux (ARM64)

platform:
  os: linux
  arch: arm64
trigger:
  event:
    - push

steps:
  - name: Test
    image: rust
    commands:
      - apt-get update && apt-get install libhtml-parser-perl zip -y
      - make test
      - >
        zip -j aarch64-unknown-linux-gnu-builds.zip
        target/debug/skyd target/debug/skysh target/debug/sky-bench
  - name: Upload artifacts
    image: plugins/s3
    settings:
      access_key:
        from_secret: s3_access_key
      secret_key:
        from_secret: s3_secret_key
      bucket: everycommit
      source: aarch64-unknown-linux-gnu-builds.zip
      target: ${DRONE_COMMIT}
      path_style: true
      endpoint:
        from_secret: storage_s3_url

---
# pipeline for building release packages
kind: pipeline
type: docker
name: Release

platform:
  os: linux
  arch: arm64
trigger:
  event:
    - tag

steps:
  - name: Package release
    image: rust
    environment:
      ARTIFACT: aarch64-linux-gnu
      VERSION: ${DRONE_TAG}
    commands:
      - apt-get update && apt-get install zip -y
      - make bundle
      - make deb
    when:
      event:
        - tag
  - name: Upload packages
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files:
        - "*.deb"
        - "*.zip"
    when:
      event:
        - tag

---
# pipeline for testing on Linux x86_64
kind: pipeline
type: docker
name: Test on Linux (x86_64)
trigger:
  event:
    exclude:
      - tag

steps:
  - name: Test
    image: rust
    commands:
      - apt update && apt-get install libhtml-parser-perl -y
      - make test
